@startuml GestionInventario
left to right direction

rectangle "Sistema de Inventario" {
    actor Administrador
    actor Cliente
    actor Vendedor

    usecase "Gestionar Productos" as UC1
    usecase "Gestionar Proveedores" as UC2
    usecase "Gestionar Clientes" as UC3
    usecase "Gestionar Ordenes" as UC4
    usecase "Realizar Pedido" as UC5
    usecase "Gestionar Cuentas" as UC6

    Administrador -[#DarkGreen]--> UC1
    Administrador -[#DarkGreen]--> UC2
    Administrador -[#DarkGreen]--> UC3
    Administrador -[#DarkGreen]--> UC4
    Administrador -[#DarkGreen]--> UC6

    Cliente -[#DarkRed]--> UC5
    Vendedor -[#Darkorange]-->UC4 
    Vendedor -[#Darkorange]--> UC1
    Vendedor -[#Darkorange]-->UC3

    UC5 -[#DarkReds]--> UC4 
}
@enduml